feat: Provide diagnostics for calcs
equinor/vscode-septic pull request #105
Opened 2023-04-21 06:59 UTC by vetlek

Features:
- Provide error reports if the expression is not parsable.
- Provide warnings for functions that are not supported in Septic.
- Provide warnings for references to Xvrs that is not in the config.

2023-04-27 14:32 UTC, einarsi requested changes
Looking good! Would be great with a runthrough before approve for merge.

Question: For most linters and syntax checkers, it is possible to either globally disable specific lints or disable them for a section or a single line. 

For Python, setup.cfg can e.g. contain 
```
ignore =
  E203
  W503
```
and lines ending with for instance "# noqa: E501" disables reporting of the line as too long.
The black formatter uses "# fmt: off" and "# fmt: on" to disable autoformatting for sections.

Any way to do something like that here, in case some of the error checks misbehave in certain cases or are annoying for some? Not saying we need it, but worth thinking about how it can be done before implementing lots and lots of syntax checks?

2023-04-28 06:21 UTC, vetlek commented on server/src/language-service/completionProvider.ts
> +        ["SopcMvr", "SopcTvr", "SopcCvr", "SopcDvr"].includes(curObj.type)
Fixed

2023-04-28 06:30 UTC, vetlek commented on server/src/language-service/documentSymbolProvider.ts
> -        ["sopcmvr", "sopccvr", "sopctvr", "sopcevr"].includes(
Delted code, not relevant.

2023-04-28 07:05 UTC, vetlek commented on package.json
> +						"error",
Based on the [documentation](https://code.visualstudio.com/api/references/contribution-points#contributes.configuration) it is not possible to use json $ref in the configuration section, thus not possible to reuse.

2023-04-28 07:08 UTC, vetlek commented
[Ref](https://github.com/equinor/vscode-septic/pull/105#pullrequestreview-1404154068): Implementing this on a global scale is easy to do. Marking certain lines is harder to implement and would require some cleaning of the files before using them in SEPTIC (i.e. removing all #...). Think we should be very sure that this is something that is needed before implementing on a local scale.

2023-05-02 09:16 UTC, einarsi approved these changes

2023-05-02 09:17 UTC, merged