chore: add pvpred attribute to mvr snippet
equinor/vscode-septic pull request #499
Opened 2024-02-19 11:51 UTC by vetlek

2024-02-19 11:53 UTC, vetlek commented
Not sure how versioning for snippets should be handled in general. Suggest that the base snippet is updated to latest, while older versions are keept with a postfix with the latest valid version

2024-02-19 14:45 UTC, einarsi requested changes

2024-02-19 14:45 UTC, einarsi commented on snippets/snippets.json
>          "description": "For SEPTIC >= v2.82"
"For SEPTIC >= v2.89" er vel korrekt her. Og så bør det helst være en snippet kalt mvr_v2.88 med description "For SEPTIC <= v2.88" som er lik denne før oppdateringen.

2024-02-19 15:25 UTC, einarsi requested changes

2024-02-19 15:25 UTC, einarsi commented on snippets/snippets.json
>          "prefix": "mvr",
```suggestion
    "Mvr_v2.88": {
        "prefix": "mvr288",
```

2024-02-19 15:25 UTC, einarsi commented on snippets/snippets.json
> +        "description": "For SEPTIC >= v2.89"
Description kan gjerne stå tom - brukes i utgangspunktet bare for eldre varianter av snippets.

2024-02-19 15:25 UTC, einarsi commented on snippets/snippets.json
>          "prefix": "mvr",
Standard brukt hittil er at tittelen inneholder siste versjon hvor snippeten var gyldig. Prefix må være unik.

Endre også description i bunnen av denne snippeten til:
```"For SEPTIC v2.82-v2.88"```

2024-02-20 09:50 UTC, einarsi approved these changes

2024-02-20 09:51 UTC, merged